const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    signupDate: "2023-01-15",
    country: "USA",
    status: "Active",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    signupDate: "2023-02-20",
    country: "Canada",
    status: "Active",
  },
  {
    id: 3,
    name: "Robert Johnson",
    email: "robert@example.com",
    signupDate: "2023-03-10",
    country: "UK",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily@example.com",
    signupDate: "2023-04-05",
    country: "Australia",
    status: "Active",
  },
  {
    id: 5,
    name: "Michael Brown",
    email: "michael@example.com",
    signupDate: "2023-05-12",
    country: "USA",
    status: "Pending",
  },
  {
    id: 6,
    name: "Sarah Wilson",
    email: "sarah@example.com",
    signupDate: "2023-06-18",
    country: "Canada",
    status: "Active",
  },
  {
    id: 7,
    name: "David Taylor",
    email: "david@example.com",
    signupDate: "2023-07-22",
    country: "UK",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Jessica Anderson",
    email: "jessica@example.com",
    signupDate: "2023-08-30",
    country: "Australia",
    status: "Active",
  },
  {
    id: 9,
    name: "Thomas Martinez",
    email: "thomas@example.com",
    signupDate: "2023-09-14",
    country: "USA",
    status: "Pending",
  },
  {
    id: 10,
    name: "Lisa Robinson",
    email: "lisa@example.com",
    signupDate: "2023-10-25",
    country: "Canada",
    status: "Active",
  },
  {
    id: 11,
    name: "Kevin Harris",
    email: "kevin@example.com",
    signupDate: "2023-11-03",
    country: "USA",
    status: "Active",
  },
  {
    id: 12,
    name: "Olivia Lewis",
    email: "olivia@example.com",
    signupDate: "2023-11-18",
    country: "UK",
    status: "Inactive",
  },
  {
    id: 13,
    name: "Nathan Clark",
    email: "nathan@example.com",
    signupDate: "2023-12-01",
    country: "Australia",
    status: "Pending",
  },
  {
    id: 14,
    name: "Grace Walker",
    email: "grace@example.com",
    signupDate: "2023-12-12",
    country: "Canada",
    status: "Active",
  },
  {
    id: 15,
    name: "Daniel Hall",
    email: "daniel@example.com",
    signupDate: "2024-01-09",
    country: "USA",
    status: "Inactive",
  },
  {
    id: 16,
    name: "Sophia Allen",
    email: "sophia@example.com",
    signupDate: "2024-01-20",
    country: "UK",
    status: "Active",
  },
  {
    id: 17,
    name: "Henry Young",
    email: "henry@example.com",
    signupDate: "2024-02-02",
    country: "Canada",
    status: "Active",
  },
  {
    id: 18,
    name: "Ava King",
    email: "ava@example.com",
    signupDate: "2024-02-17",
    country: "Australia",
    status: "Pending",
  },
  {
    id: 19,
    name: "Lucas Scott",
    email: "lucas@example.com",
    signupDate: "2024-03-01",
    country: "USA",
    status: "Active",
  },
  {
    id: 20,
    name: "Chloe Green",
    email: "chloe@example.com",
    signupDate: "2024-03-15",
    country: "UK",
    status: "Inactive",
  },
];

export default users;
